import '@/public/global.css';

export const metadata = {
  title: 'Value Glance Coding Challenge',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-1 md:m-0 bg-linear-to-t from-blue-800 to-sky-600 text-green-400">
        <div className="max-w-5xl m-auto h-[100dvh]">{children}</div>
      </body>
    </html>
  );
}
